### ISSUE TITLE
Web >Homepage>UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#1]
<img width="610" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/7acaf0f2-d08b-4030-8c95-6551675d9d75">

Careers Tab contains a different company's name

**Comment by vinayak-vayuz** [comment]
<img width="206" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9477a786-b1c2-4864-b9a2-09e9c638a8e0">
