### ISSUE TITLE
Web > Post Job > UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#100]
SBUs names in the posted jobs should be showing its logo and description on hover

**Comment by vinayak-vayuz** [comment]
Showing logo isn't possible on current tooltip so I've added the details of SBUs on Hover

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/c694655b-567b-4c95-989c-a22aa49444ed)
