### ISSUE TITLE
web > People Group > Functional > My Job

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#106]
Other SBUs jobs should be shown to the job seeker while applying.

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/5743e368-de60-47d4-b858-6616f95a30e7)

**Comment by milivayuz** [comment]
Left: List of jobs in the selected SBU
Right: Search box( with filter )
List of other SBUs Job

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/94eb3571-c29a-47ea-8169-49e622421b69)

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/13a00f27-3d80-497b-9a26-aadc5b9d263a">
Jobs are not visible
