### ISSUE TITLE
Web > Job Seeker > Functional > Homepage

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#11]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ba5ce8bc-a865-4f7c-b15f-66cb2b5a1299">

Profile Analytics's Update button is not working

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/99f91fda-1e54-45b8-8c3e-6a56d94f27c0)
