### ISSUE TITLE
web > homepage > ui

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#112]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/019b3baf-969c-4c9f-b890-52e577d128a2">

Change text to  It’s not just any internship; it’s an internship where you will gain four years of industrial experience.

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/5e36c426-589a-4341-b39b-5aacfef6f760)
