### ISSUE TITLE
Web > dashboard > UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#137]
<img width="774" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/2547f44f-e4b5-457f-8369-bd0a81039a5f">

incase of no change show white graph and write 0 %

**Comment by vinayak-vayuz** [comment]
<img width="228" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9a3261e8-4b12-41cd-a8ce-0d10c8374533">
