### ISSUE TITLE
Web > My Jobs >Functional

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#140]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/4e36bfbf-33ad-4945-bbe8-ce0593bac599">

All should contain both active and inactive

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/a0b98d74-12c9-4062-8818-777768e46992">
It's working
