### ISSUE TITLE
Web > People Group > UI > Drafted Jobs

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#147]
- [x] Change text : Drafted Jobs
- [x] remove no data found and Job applicants are eager to apply for jobs
Add
- [x] Change Text: Job seeker are eager to apply for jobs.
<img width="787" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/32775309-7869-460e-8e5b-19cbb4ddfff1">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/87aeeb92-f5fd-44f4-a51a-87db6f389882)
