### ISSUE TITLE
Web > People Group > UI > Deleted Jobs

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#148]
- [x] Add details and Restore button and remove three dots
- [x] show sbu image job title and sbu and others that are shown in normal cards
- [x] Deleted Jobs count size increase
- [x] Filter Date format VAYUZ 
- [x] Everywhere follow VAYUZ format
<img width="776" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ae715e14-a1ea-4170-891a-c6f51bd918ae">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/d855a385-a087-496c-9e64-019ff31119c7)

**Comment by milivayuz** [comment]
<img width="309" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/b65d438a-03cb-4a3c-8dba-6524cf3c0483">

Maintain the consistency all the jobs should look same
Make it like other job cards

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/e5958626-a7dc-4d57-a2d3-d1a24b500228">
