### ISSUE TITLE
No effect once the button is clicked on?

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#153]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/c3acc80f-20de-47d3-97fb-7b5711b784f0)
![Uploading image.png…]()

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/9ccdf846-6bd8-428e-8b46-57999f2d5906)
