### ISSUE TITLE
The toast message I'm getting here is wrong, especially on sign in page!! 

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#158]
![Uploading Screenshot 2024-04-08 153028.png…]()

**Comment by naveesha-vayuz** [comment]
![Screenshot 2024-04-08 153028](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/5f4de0b8-f61f-45bd-8df5-1e2834459b24)

**Comment by vinayak-vayuz** [comment]
It should be People Group instead of Employer @PrakVayuz
