### ISSUE TITLE
Basics !!! Why is the color of email input box is of another shade whereas the color of password other? Please fix this issue

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#159]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/9b2a8307-9a05-476a-8495-c5cb509aa7f9)

**Comment by vinayak-vayuz** [comment]
The color is different because you've filled it with auto suggestion. It should be normal if you'll **type** it.
