### ISSUE TITLE
Placeholders should be in italics not normal. Another change the placeholder of password to an example password.

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#160]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/aaf5610f-30b1-4104-8ab8-07912aaab34d)

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/bc44f06c-be37-4754-8c06-3b81bd834655)
