### ISSUE TITLE
On this page from where should I be able to know  if this is employer or job seeker? Also don't give me that excuse that you can look at url and all, because a user won't.

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#162]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/4e263374-e330-4054-804f-64d8f7231fde)

**Comment by vinayak-vayuz** [comment]
We're providing different link for People Group, so It's not required.
