### ISSUE TITLE
The logo is rotating wrong. Don't rotate it

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#163]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/cb404c01-2c1a-4ea3-8c0e-f830201f8990)

**Comment by vinayak-vayuz** [comment]
<img width="325" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/d3c5d775-3537-4a36-bb16-978e885a992c">

Stopped
