### ISSUE TITLE
Employer>Why is there so much space here? When we clearly dont have this much in designs?

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#164]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/fc2ebbb5-d1b1-4adb-bc2b-e1938f2cb554)

**Comment by vinayak-vayuz** [comment]
Has been removed -
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/bff92d2f-1065-45c9-b982-7db66f3fe873">
