### ISSUE TITLE
Change the icons to unfilled one's

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#166]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/2eba5f60-ffc6-4b5f-94b2-d67945c8fda3)

**Comment by vinayak-vayuz** [comment]
Please share the icons

**Comment by PrakVayuz** [comment]
@naveesha-vayuz pls share the icons

**Comment by vinayak-vayuz** [comment]
<img width="97" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/b803387e-807a-40ee-9784-98815ecbe26d">
