### ISSUE TITLE
Employer> Dashboard> Graph

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#167]
Not aligned
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/71c18975-3cce-480a-8728-4d50bb88c9d1)
Also, the size of the filter is bigger than other buttons

**Comment by vinayak-vayuz** [comment]
<img width="593" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/1f2c3aa3-3acf-4ad0-8921-209f09762400">
