### ISSUE TITLE
Web > People Group > Functional > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#175]
<img width="306" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/8f404bca-72b9-4c11-96b5-771d27f6edd0">

Notification content is not of career

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/2f11d88c-d2c2-4d9c-a96a-6390cfd37ad7)
