### ISSUE TITLE
Web > People Group > UI > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#178]
![unnamed](https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/0e6f9017-37a3-4e0e-b61e-537b7a51ae90)
Dashboard is not responsive

**Comment by vinayak-vayuz** [comment]
<img width="291" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/3b35b24b-1b7d-4191-8264-89ad09858de0">
