### ISSUE TITLE
Web > People Group > UI > Dashboard

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#180]
<img width="197" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/c8d032ce-9060-434d-846b-2a3d40131f84">

remove three dots that are coming at unnecessary titles

**Comment by vinayak-vayuz** [comment]
<img width="411" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/fd2a7e06-f1f8-469f-a419-ec359a5ba1c2">
