### ISSUE TITLE
Web > UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#181]
Maintain the same job card design throughout the platform: Posted Job , Homepage , Jobseeker feed
Apply button only for job seeker and date will be shown to employer only
![image](https://github.com/milivayuz/VAYUZ_Career/assets/156641922/0ad7f473-b101-4a8f-b70c-6c44dc3ba4ba)

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/14dbdb12-a79c-4266-871a-6a6a8728cf2b">
Design is same, but the content will definitely change on every page
