### ISSUE TITLE
Fix the text limit.

### ISSUE THREAD

**Issue by Mehulna** [milivayuz/VAYUZ_Career#184]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/93506258/8629a210-a71b-4641-95a4-f67ab1be12c5)

**Comment by milivayuz** [comment]
<img width="403" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/de93da85-d9ce-4dc2-9070-64df0739529e">

Still the same

**Comment by milivayuz** [comment]
still same

**Comment by milivayuz** [comment]
<img width="326" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/0e897e1a-b443-41c2-85cd-da0fa903f9af">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/a4c2606c-5e9c-49a5-af98-b2658a8615f3)
Max limit is set to 20
