### ISSUE TITLE
Sign up > Accepting ampersand and other symbols  as First name

### ISSUE THREAD

**Issue by Mehulna** [milivayuz/VAYUZ_Career#186]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/93506258/24672c20-ae94-43f1-a780-119b84b9936f)

**Comment by milivayuz** [comment]
<img width="310" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/91c406f0-5155-4e10-a251-cda28a5b6549">

Still issue

**Comment by milivayuz** [comment]
<img width="335" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/d7deb41f-8b2e-4001-9772-29e90cbd491b">
still issue

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/bfda0802-aae8-4043-8551-459ba1a031cd)
