### ISSUE TITLE
Sign up in > Hover effect missing , still the buttons look like inactive

### ISSUE THREAD

**Issue by Mehulna** [milivayuz/VAYUZ_Career#187]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/93506258/6b735402-4be6-4793-9507-d41b2b9ad49d)

**Comment by milivayuz** [comment]
still the issue button looks inactive

**Comment by milivayuz** [comment]
no hover effect is added

https://github.com/milivayuz/VAYUZ_Career/assets/156641922/f2fc7416-c7e4-4842-bfbd-d264a3ee0605

**Comment by vinayak-vayuz** [comment]
<img width="440" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/21a5a96f-75f6-4ee0-afc4-5fd4409c0f34">
