### ISSUE TITLE
Web > Jobseeker

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#194]
<img width="503" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ed9c7a8e-b416-492f-9fdb-6e14a20f74ec">

Facebook mentioned twice
increase padding

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/b1b84059-93ca-4e2e-82bb-ddefa2243220)

**Comment by milivayuz** [comment]
mention messenger not facebook messenger and decrease the size of copy link

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/828c1189-1bad-4245-b83b-2509d8c9f5c5)

**Comment by milivayuz** [comment]
correct the space between messenger and telegram

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/af4bd51a-50d0-4ddb-9e07-d186d912618d)
