### ISSUE TITLE
Web> People Group > Functional > Profile 

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#2]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/da51446d-1632-469b-aa04-f2196078079f">
Add the drop-down of all the roles in VAYUZ

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/7626d741-2f73-4504-a537-3432ed333a13)
