### ISSUE TITLE
Need to change the UI of notification

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#208]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/cdd188ca-dcd9-42a8-b9eb-e374c6c468da)

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/879c1aea-a0be-4e72-9140-ac85a06d45ce)
