### ISSUE TITLE
Following issues

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#209]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/27770d63-30db-4cb0-af58-3d28f2216dad)
 
1) Language Change is not working properly.
2) Also there is no signifier(icon) as to if the language has been changed or not.

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/860ed50b-3b69-4419-90cd-2cf180387c72)

**Comment by milivayuz** [comment]
partially solved

**Comment by PrakVayuz** [comment]
Jobs are  posted in english that's why Job Card is showing in english

**Comment by milivayuz** [comment]
Can't we go for translation? Is it possible

**Comment by PrakVayuz** [comment]
No , Not with the Posted Jobs
