### ISSUE TITLE
Web > Homepage > UI > Sign In

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#21]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/01a3ad97-5c0e-4200-a28f-6ab1d7f3b8e8">

Remove the Bee Recruitor Logo

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9063f746-db05-429d-9701-ca57b00a70f2">
