### ISSUE TITLE
Remove tooltip from here , it is something about which user already know about.

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#210]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/a541f5f5-26a7-4807-9281-a9fe0dc2810a)

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/f46a7fd6-91a7-41bd-a5f5-85ca8c9a2756)

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/f46a7fd6-91a7-41bd-a5f5-85ca8c9a2756)
