### ISSUE TITLE
Resume > Change the UI > Even the Most basics of Basic would die after seeing this template

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#214]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/a1cfb114-fe5f-471c-ac52-195204374f42)

**Comment by vinayak-vayuz** [comment]
The Resume Builder has been removed, so this is not valid.

**Comment by milivayuz** [comment]
New Resume Builder in phase 2
