### ISSUE TITLE
Change the UI of coming soon

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#215]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/1851203d-e34b-4366-9fe5-6beefd22b2b6)

**Comment by milivayuz** [comment]
add an illustration as well

**Comment by vinayak-vayuz** [comment]
The Resume Builder has been removed, so the issue is invalid.

**Comment by milivayuz** [comment]
New resume builder in phase 2
