### ISSUE TITLE
Web > Job Seeker > Job Detail

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#219]
<img width="954" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/50d44cc5-9224-4e2e-8f01-d76cfcbb76f5">

Progress bar is not working

**Comment by milivayuz** [comment]
still not working

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/8e7574c5-857c-4986-976a-694c222036e7)

**Comment by milivayuz** [comment]
<img width="715" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ea12a650-9dfc-433b-a4da-5ae1fcbfd7bf">

not working

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/070d8a6d-05ee-40e9-a5a5-84f8066154cd)
