### ISSUE TITLE
Web > Structure > Homepage

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#232]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/24e066da-c2a9-4235-9503-75a523b997c5">

Explore more button is missing add that

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/f2e5a024-a646-47a3-ade1-e1d38bf30701">
