### ISSUE TITLE
Web > Structure > Homepage

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#234]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/661400d3-e446-4510-b68c-741f260083be">

Add watch button in the card

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/ef309330-d2b0-4f86-8b05-0cdbe2c67382">
