### ISSUE TITLE
Post Job> Make sure to put question numbering once the user has clicked on the question

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#239]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/6219b483-ac1b-4394-9a8e-4881bc10e24f)

**Comment by PrakVayuz** [comment]
already added in placeholders & you can view numbering in job detailing page
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/9741086b-d5df-455c-ae84-c870b5cb5dd6)
