### ISSUE TITLE
Post Job > Preview > make sure to make all the progress bar working

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#240]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/08b92fb0-8c6e-4f3a-a3a7-33cfc4637520)

**Comment by vinayak-vayuz** [comment]
<img width="794" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/4f738d93-926b-4c12-8707-08c523209063">
