### ISSUE TITLE
Web > Dashboard > functional

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#246]
<img width="421" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/2641e908-2f4e-4656-a4d9-3f7d0c56c600">

On clicking job title I should be navigated to the job detail page

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/b5dcab1f-f8a8-49f5-8df2-f445589d5c5a)
