### ISSUE TITLE
Link homepage apply button to job seeker as it started working

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#247]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/f0bb9ca6-c7f0-4a7c-bab1-c2e0756b8b78">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/a75d04b2-a62e-4feb-8c26-2c08916a8757)

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/74c479b8-1bdf-4a30-8183-646ee4b0cf53">

landing on detail page and detail page have no apply button

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/8f3cb559-8aa8-42e6-a3fd-bb6e38d41816)
