### ISSUE TITLE
Remove the SBUs image from the job cards

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#248]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/eb905d3f-7759-4e45-93ad-dffff68ecc29">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/e0ccf216-a1b4-40ef-a9d8-1c30ffefab5c)
