### ISSUE TITLE
Add answers of the question added

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#250]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/66fa3910-6b04-4d8e-97f7-6884ed35d13d">

**Comment by PrakVayuz** [comment]
Answers are showing in the ATS Screen

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/07a1aa7a-058f-47e0-a774-515ff9511b71)

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/37a37fa9-f50c-4e70-afa7-62d954f25639)
A Mini View Button is there that shows responses
