### ISSUE TITLE
Merge the filter in one icon and then add that icon in the search bar

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#251]

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/d50d0b81-39e4-41ee-ab44-ca7847acea53)

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/101f3667-146f-4ca7-9c0b-6246bae8aaac">

job feed appearing twice
