### ISSUE TITLE
Need to refresh page for the update on current vacancies

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#253]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/b140a8e1-e556-4dd3-ba90-de0f453f355a">

**Comment by PrakVayuz** [comment]
This current vacancy will be show updated data everytime whenever you navigate to dashboard .
OR
we have to continuosly call vacancy api from backend
