### ISSUE TITLE
Schedule interview is not showing in the right side listing

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#255]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ccd34325-1e82-4a02-b8c8-44185bb3c2e4">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/d4b7b509-7cf2-4b28-8b41-f0798a9eebac)
