### ISSUE TITLE
Change the 0 icon graph with a straight one

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#256]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/619eec6a-27e7-419a-a2a0-af9e254f47a9">

**Comment by vinayak-vayuz** [comment]
<img width="63" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/ca047b34-2316-4f87-9cb3-c009d820519a">
