### ISSUE TITLE
Language change is not working properly on dashboard

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#257]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/29f1781e-9217-4d85-96a6-48c34d23a1df">
view all jobs
and job name

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/7e44eb56-41d3-42ec-892f-250bc7e3d7c6)

**Comment by PrakVayuz** [comment]
Job Names can't be changed ..it comes in the same language to which they are posted

**Comment by milivayuz** [comment]
alright
no further update can be possible
