### ISSUE TITLE
Once notification is open do not show the notification count over icon

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#258]
<img width="331" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/4c268991-5087-4d14-bec0-10ed5d17c7ee">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/e8f99981-329a-42fc-8760-afe9d7f521cf)
