### ISSUE TITLE
Correct the date in the graph

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#259]
<img width="644" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/c090dd25-8be8-44ea-b1a2-e7c5adcca6bd">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/7104dc5c-0815-453f-81b9-360048ce54cc)
