### ISSUE TITLE
Go with blue shade that used in the website instead of purple

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#260]
<img width="629" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/68fdde14-d502-484a-bc08-17581f2cdbc6">

**Comment by vinayak-vayuz** [comment]
<img width="625" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/e87c2218-d4a8-4c8d-a82d-43eeede9ee51">
