### ISSUE TITLE
Graph is not working properly

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#261]
<img width="616" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/2e434bbc-4f4c-4962-9368-185543cbb248">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/084cd848-e0dd-4d55-8b17-20740521afd9)
