### ISSUE TITLE
Images are missing in the hero section

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#262]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/6c27b1c8-e718-4a57-a905-ff60acbdb1f7">
Add images

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9b548399-d20f-4e93-88b7-0f37d6b50672">
