### ISSUE TITLE
Unneccessary gap

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#263]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/d78055ff-e484-4e97-ab66-e269d71a7f9a">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/77f82b90-ec3d-42cf-8d0c-870cba85691f">
