### ISSUE TITLE
Left side Should be clickable

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#264]
<img width="215" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ba29be45-41e8-4b00-9f01-3edce1479467">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/0303fa1f-87ab-45cf-b0b9-a05f12f5c84a)
