### ISSUE TITLE
Video banner with a overlay in the background

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#265]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/d91077c8-f3a6-4b6c-a1bb-e600c3376117">

**Comment by vinayak-vayuz** [comment]
<img width="958" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9235c888-e61d-4ea0-bf87-934737bfd054">
