### ISSUE TITLE
Lot of in next line

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#266]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/a0252888-ee04-4e68-beb6-2acf409dcf89">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/ecc33f74-d735-4f23-be39-39c298e13f34)
