### ISSUE TITLE
Add real text

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#267]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/aa13cd71-0494-48f8-a7da-19170a0deeeb">

**Comment by vinayak-vayuz** [comment]
share text @milivayuz

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/824bfba0-2b58-4808-9e13-0277410c1fb7">
