### ISSUE TITLE
Remove tool tip: View more

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#268]
<img width="269" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/640e1383-c271-4dca-bb88-c5577ae75f09">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/74fa1995-c685-43ca-93ee-88ff5af3e0c7)
