### ISSUE TITLE
Add share on three dot

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#269]
<img width="269" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/de8d7de9-41b9-4e90-a06a-40c42b363b83">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9deb3827-0dbf-462f-97b4-df099d35c393)
