### ISSUE TITLE
Add real text not the dummy

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#270]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/c4ee1316-b99e-4bea-89a4-ca1ffd9a971c">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/cea77d67-6bba-40a6-9bf7-d8861e740080)
