### ISSUE TITLE
Change text: Sign in to Opportunities

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#272]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/f4cc1005-a015-4420-9e0b-0c40c8ae2705">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/98be6857-4dca-404e-8867-79118106a1dd)
