### ISSUE TITLE
Data is not showing up

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#274]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/2d41d5f9-1fa9-439c-bd91-85ec21e88fa4">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/17acbe51-b5d1-422d-88d9-a640a5e455a9)
