### ISSUE TITLE
Align Search with the tabs of categorization

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#277]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/f791ea0f-b202-457e-a39a-81435c87f04d">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/c2f26564-82f9-412e-b516-8c70ed3858de">
