### ISSUE TITLE
Remove saved jobs

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#282]
<img width="181" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/bf64e79a-06ab-4acc-b583-6addac0edfa0">

**Comment by vinayak-vayuz** [comment]
<img width="173" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/8d353e13-f915-408f-bf23-6861c10cab98">
