### ISSUE TITLE
Mention settings instead of settings & privacy

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#283]
<img width="181" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ff36ec40-0cbc-4e42-be54-b95a90394826">

**Comment by vinayak-vayuz** [comment]
<img width="218" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/25224ba4-9b0b-414c-9265-efce7cf77e5f">
