### ISSUE TITLE
Make it in the listing format

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#284]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/25493c98-0bc9-4fb6-954a-a11401526727">

Make it in the listing format

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/e49fa67f-bef6-4cc6-b2a9-9c70e0ac03dc">
