### ISSUE TITLE
Make it a drop down as mentioned below

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#287]
<img width="802" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/330bc078-79d0-439c-811f-232a2652aafd">

All active inactive

**Comment by vinayak-vayuz** [comment]
<img width="795" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/be04948b-1771-4e12-bdfe-7993ffe5f18d">
