### ISSUE TITLE
Make card like homepage i.e new design

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#288]
<img width="812" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/c93a3479-8d7e-4ebb-9837-a21deb554d17">

**Comment by vinayak-vayuz** [comment]
<img width="273" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/f2efa9ee-9e6f-401b-adbb-6dc55f3f510e">
