### ISSUE TITLE
Make card like homepage i.e new design

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#289]
In drafted and deleted jobs

**Comment by vinayak-vayuz** [comment]
<img width="266" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/53e49e2f-bafb-4166-9788-62f3e8a1c98e">
<img width="306" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/3060f522-0d75-46f3-b276-962ec0b2e842">
