### ISSUE TITLE
Web > Homepage > Sign Up

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#29]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/2ae6f428-030d-42ca-adac-68467ddecd6f">

Initial input boxes are not visible

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/4b8b0c7d-a03d-4de0-a8a5-fefc8acfe0a9)
