### ISSUE TITLE
Remove offer letter column

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#291]
<img width="794" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/e31d8fe6-5f5b-4f00-b0f7-2315e32f01f9">

**Comment by vinayak-vayuz** [comment]
<img width="803" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/3889ac67-6fd2-46ac-bbad-8920d0336d0b">
