### ISSUE TITLE
Switch offer letter with CV Matchmaking score

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#293]
<img width="796" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/d3e50452-11bf-4496-b248-10a7f474ab1f">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/ad5223b7-78c8-4fca-9323-e4c32c7563fe)
