### ISSUE TITLE
Change text: Opportunities to Openings

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#296]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/1d295ec1-b7be-4388-9dcf-b9af1cd80e4c">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/ee1e3c0f-6d13-4293-b823-09dcb2e2de52">
