### ISSUE TITLE
LOT OF __ in new line together

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#297]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/1011ee0c-5101-4028-a07d-4a0960e21aee">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/1411ebc0-0dba-4786-a98a-232c361b5282">
