### ISSUE TITLE
add oath ceremoney banner in background

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#298]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/26a7ba53-7559-485c-823c-63db9008ace2">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/7ca70633-9af5-4f26-b69a-d02b7db8a16d">
