### ISSUE TITLE
add animation on a 

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#299]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/7a1d870a-30c4-42c4-8481-8aaac49d1b0f">

**Comment by vinayak-vayuz** [comment]
It wasn't about animation, we just had to differentiate between other words.
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/6824c1d1-2fa2-4352-a3ed-24312d6671da">
