### ISSUE TITLE
Web > Dashboard> UI > Post Job

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#3]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/27c935fc-fe1a-4427-9fef-902de460875a">

Remove following from the form except employer type:
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/54b6f616-7b4a-4d72-b6e9-d3b4392f9cbc">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/66545d88-c91b-48e3-b282-00856e6d9602">
