### ISSUE TITLE
Web > People Group > Homepage > Sign Up

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#30]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/70f880a5-7f6e-4e39-ac49-7735cc05e7fb">

Sign Up appears somewhere in the landing page instead of a pop-up card format on click

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/f14e0a73-c040-4784-a332-b6007bfb7325)
