### ISSUE TITLE
Make it a ID Card : photo of VAYUZers

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#300]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ff1c2471-257f-4073-8147-09ef46c94799">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/c1d3a682-94ce-45ce-85a0-d850d113cdfa">

**Comment by milivayuz** [comment]
add space in the ID Card on right

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/675ea45c-308e-40f8-82b4-625269be5e87">
Added spacing as center is not looking good
