### ISSUE TITLE
Data is missing

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#301]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/79bd2649-e9c9-4383-8f85-90f22e5b914f">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/96d063e2-b89f-49b8-956c-b4039661bc80)
