### ISSUE TITLE
Add all events

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#302]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/337d6b0e-58fd-4d4e-add4-3ffef49d4048">

**Comment by vinayak-vayuz** [comment]
Events has been added.

**Comment by vinayak-vayuz** [comment]
@milivayuz  Please share banner for -

1. Innovation Day
2. Confluence
3. VIP Lounge

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/c07393ca-0fca-47ff-b318-41003bcd1825">

**Comment by milivayuz** [comment]
Videos are still not added

**Comment by vinayak-vayuz** [comment]
Added the available links
