### ISSUE TITLE
Default event: Horcrux

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#303]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/648a46ae-77d9-4923-9809-1395c58c1427">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/2274bfc5-2758-4e3a-bd7e-b0d7cdb43d40">
