### ISSUE TITLE
Web > People Group > Homepage > Sign Up

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#31]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/dd2d63f2-c93b-420d-b150-89cbbb65293c">

Remove the Bee Recruiter Logo

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/0e178496-2077-409a-9d81-c1aec2c45c70)
