### ISSUE TITLE
Remove this tooltip

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#340]
<img width="958" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/47156abd-6e5f-4a1e-b04b-0cdf3325c78f">

**Comment by vinayak-vayuz** [comment]
<img width="446" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/c41bef5f-0539-4ca1-9049-8ec0c52ae3e6">
