### ISSUE TITLE
Reduce the space after title

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#342]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/3aa55db8-125c-493d-8071-3dbcbf7290a8">

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9bce9e54-35a8-4543-a5a0-b94d2d8d274d">
