### ISSUE TITLE
I am yet to visit the phone no. still it is giving me alert of blank

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#346]
<img width="469" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/28bc5641-be42-4945-8d93-64a2bc2ae22f">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/85c83d6d-b82c-41ad-8add-5d791d93e89f)
