### ISSUE TITLE
Validation issue: Able to add 2 names while i should be able to add only 1

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#348]
<img width="365" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/6c151cd0-6bff-4f63-88c9-363d5aff2884">

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/7f237009-deb8-4873-8a3d-1ac9f01f3125)
