### ISSUE TITLE
Web > People Group > Functional > Post Job

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#5]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/4f0bf753-e6f2-4f82-a7a8-1b0f83d88588">

Make it optional not compulsory

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/92c450f8-197d-440a-b697-e1c37f4403bb)
