### ISSUE TITLE
Web > Job Seeker > Profile 

### ISSUE THREAD

**Issue by vinayak-vayuz** [milivayuz/VAYUZ_Career#62]
<img width="354" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/fd11da31-e21c-486b-bb16-9ccb60a10602">

**Comment by vinayak-vayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/128778447/9537f9b5-f8f7-4697-8182-d08190117804)

**Comment by murtaza030** [comment]
please assign this issue
