### ISSUE TITLE
Web > People Group > Functional > My Jobs

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#7]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/ab5cb559-7483-4f40-b22e-2353edefd835">

Once the job is posted it should get active instead of inactive

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/9d232822-1386-4263-b000-095a72ca0bee)
