### ISSUE TITLE
Web > Sign in > UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#76]
<img width="376" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/3702aca8-96b8-4f03-ab8e-87daf2abe5e4">

Email ID is not visible

**Comment by vinayak-vayuz** [comment]
<img width="444" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/0a8a875f-ad8c-4f9d-a53e-f3bfae892ec2">
