### ISSUE TITLE
Web > Job Seeker > Functional > Course

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#9]
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/8986bea8-999b-446b-8868-24a114a2e5c1">

Remove Course Setion

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/8535838c-4416-499b-9627-6a3844d7b7f1)
