### ISSUE TITLE
Web > Dashbboard > Functional

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#94]
<img width="958" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/da2925c9-674c-4554-bde3-1228bb2e023c">

Current Vacancies should have all the jobs instead of the ones i posted but the edit access should only be to the one who is posted

**Comment by PrakVayuz** [comment]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/158542726/ca8c5da5-32a0-4a84-a38c-d47ab725c4e3)
