### ISSUE TITLE
Web > Job Seeker > Functional > Job Feed

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#95]
<img width="958" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/e6a67ed8-2126-4b84-afdb-f6949c3cd1bb">
 view all is not working properly in job feed

**Comment by PrakVayuz** [comment]
Automatic API Calls are added ...that shows old jobs when you scroll down
