### ISSUE TITLE
Web > UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#98]
The complete website font should be light and minimal
The font should be light.

**Comment by vinayak-vayuz** [comment]
I can't change website font weight or color according to my preferences please share example & also be specific with the pages. @milivayuz

**Comment by milivayuz** [comment]
Like the People Group's Dashboard make the calendar in the same way light not bold

**Comment by vinayak-vayuz** [comment]
<img width="169" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/128778447/adb91417-bf04-46f9-b90a-c992b7f9f9d1">
I've changed mostly, if you see bold font somewhere please report it
